import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Set.Card
import Mathlib.Logic.Equiv.Basic
import Mathlib.Data.List.Basic
import Mathlib.Data.Int.Basic
import Mathlib.Tactic
import AbsAlg.Group_basic

open MyGroup

-- Powers of an element
def npower {G : Type} [MyGroup G] (g : G) (n : ℕ) : G :=
  match n with
  | 0 => e
  | Nat.succ n => g * (npower g n)

def zpower {G : Type} [MyGroup G] (g : G) (n : ℤ) : G :=
  match n with
  | Int.ofNat k   => npower g k
  | Int.negSucc k => (npower g (k + 1))⁻¹


theorem npower_succ {G : Type} [MyGroup G] (g : G) (n : ℕ) :
    npower g (n +1) = g * npower g n := by
  rfl

theorem npower_comm {G : Type} [MyGroup G] (g : G) (n : ℕ) :
    g * npower g n = npower g n * g := by
  induction n with
  | zero =>
    simp only [npower]
    rw [MyGroup.mul_one, MyGroup.one_mul]
  | succ n ih =>
    rw [npower_succ, MyGroup.mul_assoc, ← ih, ← MyGroup.mul_assoc]

lemma npower_succ' {G : Type} [MyGroup G] (g : G) (n : ℕ) :
  npower g (n + 1) = npower g n * g := by
  rw [← npower_comm, npower]


theorem zpower_succ {G : Type} [MyGroup G] (g : G) (n : ℤ) :
  zpower g (n + 1) = (zpower g n) * g := by
  cases n with
  | ofNat n =>
    simp only [zpower]
    exact npower_succ' g n
  | negSucc n =>
    cases n with
    | zero =>
      simp [zpower, npower, MyGroup.mul_one, MyGroup.mul_left_inv]
    | succ n =>
      simp only [zpower]
      rw [npower, MyGroup.mul_inv_reverse, MyGroup.mul_assoc,
          MyGroup.mul_left_inv, MyGroup.mul_one]
      rfl

theorem zpower_pred {G : Type} [MyGroup G] (g : G) (n : ℤ) :
  zpower g (n - 1) = (zpower g n) * g⁻¹ := by
  have h := zpower_succ g (n - 1)
  rw [Int.sub_add_cancel] at h
  rw [h, MyGroup.mul_assoc, MyGroup.mul_right_inv, MyGroup.mul_one]

-- g^{n+m} = g^n * g^m
theorem zpower_add {G : Type} [MyGroup G] (g : G) (n m : ℤ) :
    zpower g (n + m) = (zpower g n) * (zpower g m) := by
  refine Int.inductionOn' m 0 ?zero ?succ ?pred
  case zero =>
    rw [Int.add_zero]
    dsimp [zpower]
    rw [npower, MyGroup.mul_one]
  case succ =>
    intro k hk ih
    rw [← Int.add_assoc, zpower_succ, ih, zpower_succ, MyGroup.mul_assoc]
  case pred =>
    intro k hk ih
    have : n + (k - 1) = (n + k) - 1 := by omega
    rw [this, zpower_pred, ih, MyGroup.mul_assoc, ← zpower_pred]


-- Cyclic Subgroup generated by g
def cyclic_subgroup {G : Type} [MyGroup G] (g : G) : MySubgroup G where
  carrier := { x | ∃ n : ℤ, x = zpower g n}
  one_mem := by
    use 0
    rfl
  mul_mem := by
    intros a b ha hb
    rcases ha with ⟨n, hn⟩
    rcases hb with ⟨m, hm⟩
    use n + m
    rw [hn, hm]
    exact (zpower_add g n m).symm
  inv_mem := by
    intros a n
    rcases n with ⟨n, hn⟩
    use -n
    rw [hn]
    match n with
  | Int.ofNat 0 =>
    simp only [zpower, npower, Int.ofNat_eq_natCast, CharP.cast_eq_zero, neg_zero]
    exact inv_one
  | Int.ofNat (Nat.succ k) =>
    rfl
  | Int.negSucc k =>
    simp only [zpower, Int.neg_negSucc, Nat.cast_add, Nat.cast_one]
    exact inv_inv (npower g (k + 1))
