import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Set.Card
import Mathlib.Logic.Equiv.Basic
import Mathlib.Data.List.Basic
import Mathlib.Tactic
import AbsAlg.Group_basic

open MyGroup


-- Powers of an element
def npower {G : Type} [MyGroup G] (g : G) (n : ℕ) : G :=
  match n with
  | 0 => e
  | Nat.succ n => g * (npower g n)

def zpower {G : Type} [MyGroup G] (g : G) (n : ℤ) : G :=
  match n with
  | Int.ofNat k   => npower g k
  | Int.negSucc k => (npower g (k + 1))⁻¹

notation g " # " n => zpower g n

theorem npower_add {G : Type} [MyGroup G] (g : G) (n m : ℕ) :
    npower g (n + m) = (npower g n) * (npower g m) := by
  induction n with
  | zero =>
    simp only [zero_add, npower]
    rw [MyGroup.one_mul]
  | succ n ih =>
    rw [Nat.succ_add]
    simp only [npower]
    rw [ih]
    rw [MyGroup.mul_assoc]

theorem zpower_add {G : Type} [MyGroup G] (g : G) (n m : ℤ) :
    zpower g (n + m) = (zpower g n) * (zpower g m) := by
  match n, m with
  | Int.ofNat n, Int.ofNat m =>
    change npower g (n + m) = npower g n * npower g m
    exact npower_add g n m

  | Int.negSucc n, Int.negSucc m =>
    simp only [zpower, Int.negSucc_add_negSucc, Nat.succ_eq_add_one]
    rw [npower_add, mul_inv_reverse]
    sorry

  | Int.ofNat n, Int.negSucc m =>
    sorry

  | Int.negSucc n, Int.ofNat m =>
    sorry


-- Cyclic Subgroup generated by g
def cyclic_subgroup {G : Type} [MyGroup G] (g : G) : MySubgroup G where
  carrier := { x | ∃ n : ℤ, x = g # n}
  one_mem := by
    use 0
    rfl
  mul_mem := by
    intros a b ha hb
    rcases ha with ⟨n, hn⟩
    rcases hb with ⟨m, hm⟩
    use n + m
    rw [hn, hm]
    exact (zpower_add g n m).symm
  inv_mem := by
    intros a n
    rcases n with ⟨n, hn⟩
    use -n
    rw [hn]
    match n with
  | Int.ofNat 0 =>
    simp only [zpower, npower, Int.ofNat_eq_natCast, CharP.cast_eq_zero, neg_zero]
    exact inv_one
  | Int.ofNat (Nat.succ k) =>
    rfl
  | Int.negSucc k =>
    simp only [zpower, Int.neg_negSucc, Nat.cast_add, Nat.cast_one]
    exact inv_inv (npower g (k + 1))
